package view;

import view.Cadastrar.CadastrarBlocos;
import view.Cadastrar.CadastrarDepartamentos;
import view.Cadastrar.CadastrarHorarios;
import view.Cadastrar.CadastrarSalas;
import view.Cadastrar.CadastrarTpsSala;
import view.Cadastrar.CadastrarUsuarios;
import view.Editar.EditarBlocos;
import view.Editar.EditarDepartamentos;
import view.Editar.EditarHorarios;
import view.Editar.EditarSalas;
import view.Editar.EditarTpsSala;
import view.Editar.EditarUsuarios;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * 
 *
 * @author Aluno
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    TelaReservas telareservas = new TelaReservas();
    TelaConsultar telaconsultar = new TelaConsultar();

    public TelaPrincipal() {
        telareservas.setVisible(false);
        telaconsultar.setVisible(false);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        txtConsultar = new java.awt.Button();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        scrollbar1 = new java.awt.Scrollbar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jpPrincipal = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmConsultar = new javax.swing.JMenu();
        jmReservas = new javax.swing.JMenu();
        jmGerenciar = new javax.swing.JMenu();
        jmCadastrar = new javax.swing.JMenu();
        jmCadSalas = new javax.swing.JMenuItem();
        jmCadBlocos = new javax.swing.JMenuItem();
        jmCadTipodeSalas = new javax.swing.JMenuItem();
        jmCadHorarios = new javax.swing.JMenuItem();
        jmCadDepartamento = new javax.swing.JMenuItem();
        jmCadUsuarios = new javax.swing.JMenuItem();
        jmEditar = new javax.swing.JMenu();
        jmEditarSalas = new javax.swing.JMenuItem();
        jmEditarBlocos = new javax.swing.JMenuItem();
        jmEditarTipodeSalas = new javax.swing.JMenuItem();
        jmEditarHorarios = new javax.swing.JMenuItem();
        jmEditarDepartamento = new javax.swing.JMenuItem();
        jmEditarUsuarios = new javax.swing.JMenuItem();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setTitle("Tela principal");

        txtConsultar.setLabel("Consultar");
        txtConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultarActionPerformed(evt);
            }
        });

        jTextField1.setText("Informações da sala que você quer");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("CONSULTAR SALA");

        jLabel2.setText("Informe a data");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Informe o código, o tipo ou \numa palavra-chave para enco-\nntrar a sala que deseja consul-\ntar a disponibilidade.  ");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(29, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(txtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(txtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Champinho");

        panel2.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"A040 (X horários disponíveis)"},
                {"P105 (X horários disponíveis)"},
                {"A145 (X horários disponíveis)"},
                {"K009 (X horários disponíveis)"},
                {"P205 (X horários disponíveis)"}
            },
            new String [] {
                "SALAS ENCONTRADAS"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(scrollbar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollbar1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Consultar sala");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reservas");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Gerenciar");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Salas");
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Blocos");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Tipo de salas");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Horários");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Departamento");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Usuários");
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        jFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpPrincipal.setPreferredSize(new java.awt.Dimension(647, 409));

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        jmConsultar.setText("Consultar");
        jmConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmConsultarMouseClicked(evt);
            }
        });
        jmConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultarActionPerformed(evt);
            }
        });
        jMenuBar2.add(jmConsultar);

        jmReservas.setText("Reservas");
        jmReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmReservasMouseClicked(evt);
            }
        });
        jMenuBar2.add(jmReservas);

        jmGerenciar.setText("Gerenciar");
        jmGerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmGerenciarActionPerformed(evt);
            }
        });

        jmCadastrar.setText("Cadastrar");

        jmCadSalas.setText("Salas");
        jmCadSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadSalasActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmCadSalas);

        jmCadBlocos.setText("Blocos");
        jmCadBlocos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadBlocosActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmCadBlocos);

        jmCadTipodeSalas.setText("Tipo de salas");
        jmCadTipodeSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadTipodeSalasActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmCadTipodeSalas);

        jmCadHorarios.setText("Horários");
        jmCadHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadHorariosActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmCadHorarios);

        jmCadDepartamento.setText("Departamento");
        jmCadDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadDepartamentoActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmCadDepartamento);

        jmCadUsuarios.setText("Usuários");
        jmCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadUsuariosActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmCadUsuarios);

        jmGerenciar.add(jmCadastrar);

        jmEditar.setText("Editar");

        jmEditarSalas.setText("Salas");
        jmEditarSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEditarSalasActionPerformed(evt);
            }
        });
        jmEditar.add(jmEditarSalas);

        jmEditarBlocos.setText("Blocos");
        jmEditarBlocos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEditarBlocosActionPerformed(evt);
            }
        });
        jmEditar.add(jmEditarBlocos);

        jmEditarTipodeSalas.setText("Tipo de salas");
        jmEditarTipodeSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEditarTipodeSalasActionPerformed(evt);
            }
        });
        jmEditar.add(jmEditarTipodeSalas);

        jmEditarHorarios.setText("Horários");
        jmEditarHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEditarHorariosActionPerformed(evt);
            }
        });
        jmEditar.add(jmEditarHorarios);

        jmEditarDepartamento.setText("Departamento");
        jmEditarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEditarDepartamentoActionPerformed(evt);
            }
        });
        jmEditar.add(jmEditarDepartamento);

        jmEditarUsuarios.setText("Usuários");
        jmEditarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEditarUsuariosActionPerformed(evt);
            }
        });
        jmEditar.add(jmEditarUsuarios);

        jmGerenciar.add(jmEditar);

        jMenuBar2.add(jmGerenciar);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jmConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultarActionPerformed
    
    }//GEN-LAST:event_jmConsultarActionPerformed

    private void jmCadSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadSalasActionPerformed
        CadastrarSalas cadsalas = new CadastrarSalas();
        cadsalas.setVisible(true);
    }//GEN-LAST:event_jmCadSalasActionPerformed

    private void jmEditarSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEditarSalasActionPerformed
        EditarSalas editarsalas = new EditarSalas();
        editarsalas.setVisible(true);

    }//GEN-LAST:event_jmEditarSalasActionPerformed

    private void jmGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmGerenciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmGerenciarActionPerformed

    private void jmConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmConsultarMouseClicked
        if(!telaconsultar.isVisible()){
            jpPrincipal.add(telaconsultar).setBounds(0,0,647,409);
            telaconsultar.setVisible(true);
            telareservas.setVisible(false);
        }else{
            System.out.println("Tela já aberta");
        }

    }//GEN-LAST:event_jmConsultarMouseClicked

    private void jmReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmReservasMouseClicked
        if(!telareservas.isVisible()){
            jpPrincipal.add(telareservas).setBounds(0,0,647,409);
            telareservas.setVisible(true);
            telaconsultar.setVisible(false);
        }else{
            System.out.println("Tela já aberta");
        }

    }//GEN-LAST:event_jmReservasMouseClicked

    private void jmEditarBlocosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEditarBlocosActionPerformed
        
        EditarBlocos editarblocos = new EditarBlocos();
        editarblocos.setVisible(true);


    }//GEN-LAST:event_jmEditarBlocosActionPerformed

    private void jmEditarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEditarDepartamentoActionPerformed
        EditarDepartamentos editardepartamentos = new EditarDepartamentos();
        editardepartamentos.setVisible(true);

    }//GEN-LAST:event_jmEditarDepartamentoActionPerformed

    private void jmEditarHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEditarHorariosActionPerformed
        EditarHorarios editarhorarios = new EditarHorarios();
        
        editarhorarios.setVisible(true);
    }//GEN-LAST:event_jmEditarHorariosActionPerformed

    private void jmCadBlocosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadBlocosActionPerformed
        CadastrarBlocos cadblocos = new CadastrarBlocos();
        cadblocos.setVisible(true);


    }//GEN-LAST:event_jmCadBlocosActionPerformed

    private void jmCadTipodeSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadTipodeSalasActionPerformed
        CadastrarTpsSala cadtiposala = new CadastrarTpsSala();
        cadtiposala.setVisible(true);


    }//GEN-LAST:event_jmCadTipodeSalasActionPerformed

    private void jmCadHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadHorariosActionPerformed
        CadastrarHorarios cadhorarios = new CadastrarHorarios();
        cadhorarios.setVisible(true);


    }//GEN-LAST:event_jmCadHorariosActionPerformed

    private void jmCadDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadDepartamentoActionPerformed
        CadastrarDepartamentos caddepartamentos = new CadastrarDepartamentos();
        caddepartamentos.setVisible(true);

    }//GEN-LAST:event_jmCadDepartamentoActionPerformed

    private void jmCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadUsuariosActionPerformed
        CadastrarUsuarios cadusuarios = new CadastrarUsuarios();
        cadusuarios.setVisible(true);

    }//GEN-LAST:event_jmCadUsuariosActionPerformed

    private void jmEditarTipodeSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEditarTipodeSalasActionPerformed
        EditarTpsSala editartiposala = new EditarTpsSala();
        editartiposala.setVisible(true);

    }//GEN-LAST:event_jmEditarTipodeSalasActionPerformed

    private void jmEditarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEditarUsuariosActionPerformed
        EditarUsuarios editarusuarios = new EditarUsuarios();
        editarusuarios.setVisible(true);

    }//GEN-LAST:event_jmEditarUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuItem jmCadBlocos;
    private javax.swing.JMenuItem jmCadDepartamento;
    private javax.swing.JMenuItem jmCadHorarios;
    private javax.swing.JMenuItem jmCadSalas;
    private javax.swing.JMenuItem jmCadTipodeSalas;
    private javax.swing.JMenuItem jmCadUsuarios;
    private javax.swing.JMenu jmCadastrar;
    private javax.swing.JMenu jmConsultar;
    private javax.swing.JMenu jmEditar;
    private javax.swing.JMenuItem jmEditarBlocos;
    private javax.swing.JMenuItem jmEditarDepartamento;
    private javax.swing.JMenuItem jmEditarHorarios;
    private javax.swing.JMenuItem jmEditarSalas;
    private javax.swing.JMenuItem jmEditarTipodeSalas;
    private javax.swing.JMenuItem jmEditarUsuarios;
    private javax.swing.JMenu jmGerenciar;
    private javax.swing.JMenu jmReservas;
    private javax.swing.JPanel jpPrincipal;
    private java.awt.Panel panel2;
    private java.awt.Scrollbar scrollbar1;
    private java.awt.Button txtConsultar;
    // End of variables declaration//GEN-END:variables
}
