/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Database.SalaDao;
import Model.Sala;
import static Util.Utility.setModal;
import View.Editar.EditarUsuario;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Renato
 */
public class TelaConsultar extends javax.swing.JPanel {
    public String dataReserva;
    
    /**
     * Creates new form TelaReservas
     */
    public TelaConsultar() {
           initComponents();
           jlistResultadosBusca.setModel(new DefaultListModel());
    }
    
    public void focusInput() {
        jtDadosdePesquisa.requestFocus();
    }
    
    public void limpaResults() {
        DefaultListModel listModel = (DefaultListModel) jlistResultadosBusca.getModel();
        listModel.removeAllElements();
    }
    
    public void limpaConsulta() {
        jtDadosdePesquisa.setText("");
        jCalendar1.setDate(new Date());
        limpaResults();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jpConsultarSala = new javax.swing.JPanel();
        jtDadosdePesquisa = new javax.swing.JTextField();
        jlSubtituloData = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelDataEscolhida = new javax.swing.JLabel();
        jpResultadosdaBusca = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistResultadosBusca = new javax.swing.JList<>();
        jbuttonConsultar = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setMaximumSize(new java.awt.Dimension(700, 450));
        setMinimumSize(new java.awt.Dimension(700, 450));
        setPreferredSize(new java.awt.Dimension(700, 450));
        setVerifyInputWhenFocusTarget(false);

        jpConsultarSala.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONSULTAR SALA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jpConsultarSala.setPreferredSize(new java.awt.Dimension(400, 430));

        jtDadosdePesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDadosdePesquisaActionPerformed(evt);
            }
        });

        jlSubtituloData.setText("Informe a data");

        jCalendar1.setDecorationBackgroundVisible(false);
        jCalendar1.setDoubleBuffered(false);
        jCalendar1.setMinSelectableDate(new java.util.Date(-62135755103000L));
        jCalendar1.setNullDateButtonText("");
        jCalendar1.setWeekOfYearVisible(false);
        jCalendar1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCalendar1PropertyChange(evt);
            }
        });

        jLabel1.setText("<html>Informe o código, o tipo ou uma palavra-chave para encontrar a sala que deseja consultar a disponibilidade. </html>");

        jLabel2.setText("Informações da sala que você quer");

        javax.swing.GroupLayout jpConsultarSalaLayout = new javax.swing.GroupLayout(jpConsultarSala);
        jpConsultarSala.setLayout(jpConsultarSalaLayout);
        jpConsultarSalaLayout.setHorizontalGroup(
            jpConsultarSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConsultarSalaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpConsultarSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtDadosdePesquisa)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpConsultarSalaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpConsultarSalaLayout.createSequentialGroup()
                        .addComponent(jlSubtituloData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(jLabelDataEscolhida, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpConsultarSalaLayout.setVerticalGroup(
            jpConsultarSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConsultarSalaLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtDadosdePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpConsultarSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSubtituloData)
                    .addComponent(jLabelDataEscolhida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpResultadosdaBusca.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESULTADOS DA BUSCA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jpResultadosdaBusca.setPreferredSize(new java.awt.Dimension(271, 428));

        jlistResultadosBusca.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlistResultadosBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlistResultadosBuscaMouseClicked(evt);
            }
        });
        jlistResultadosBusca.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlistResultadosBuscaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jlistResultadosBusca);

        jbuttonConsultar.setText("Consultar");
        jbuttonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpResultadosdaBuscaLayout = new javax.swing.GroupLayout(jpResultadosdaBusca);
        jpResultadosdaBusca.setLayout(jpResultadosdaBuscaLayout);
        jpResultadosdaBuscaLayout.setHorizontalGroup(
            jpResultadosdaBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpResultadosdaBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpResultadosdaBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(jbuttonConsultar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpResultadosdaBuscaLayout.setVerticalGroup(
            jpResultadosdaBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpResultadosdaBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbuttonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpConsultarSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpResultadosdaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpConsultarSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpResultadosdaBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void jtDadosdePesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDadosdePesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDadosdePesquisaActionPerformed

    private void jlistResultadosBuscaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlistResultadosBuscaValueChanged
    }//GEN-LAST:event_jlistResultadosBuscaValueChanged

    private void jlistResultadosBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlistResultadosBuscaMouseClicked
        if(evt.getClickCount()==2){
            int index = jlistResultadosBusca.getSelectedIndex();
            Object selecionada = jlistResultadosBusca.getModel().getElementAt(index);
            Sala sala = (Sala) selecionada;
            setModal(new DescricaoSala(sala, dataReserva), null, 367, 565, null);
        }
    }//GEN-LAST:event_jlistResultadosBuscaMouseClicked

    private void jbuttonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonConsultarActionPerformed
        String dadosSala = jtDadosdePesquisa.getText();
        dataReserva = new SimpleDateFormat("yyyy-MM-dd").format(jCalendar1.getDate());
        //System.out.println(dadosSala + "\n" + dataEscolhida);
        
        // Fazer a consulta no BD
        SalaDao sld = new SalaDao();
        
        if(!dadosSala.equals("")){
            List listaSalas = sld.buscaSalas(dadosSala);
            Sala[] arrSalas = new Sala[listaSalas.size()];
            listaSalas.toArray(arrSalas);

            DefaultListModel list = new DefaultListModel();

            if(listaSalas.size() == 0){
                JOptionPane.showMessageDialog(null, "Nenhuma sala encontrada", null, JOptionPane.PLAIN_MESSAGE);
            } else {
                for (int i = 0; i < listaSalas.size(); i++){
                    list.addElement(arrSalas[i]);
                }
            }

            jlistResultadosBusca.setModel(list);
        } else {
            JOptionPane.showMessageDialog(null, "Digite alguma informação sobre a sala para pesquisar", "", JOptionPane.PLAIN_MESSAGE);
            jtDadosdePesquisa.requestFocus();
        }
        
    }//GEN-LAST:event_jbuttonConsultarActionPerformed

    private void jCalendar1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCalendar1PropertyChange
        String dataEscolhida = new SimpleDateFormat("dd/MM/yyyy").format(jCalendar1.getDate());
        jLabelDataEscolhida.setText("<html>Data selecionada: <b>" + dataEscolhida + "</b></html>");
    }//GEN-LAST:event_jCalendar1PropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDataEscolhida;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbuttonConsultar;
    private javax.swing.JLabel jlSubtituloData;
    private javax.swing.JList<String> jlistResultadosBusca;
    private javax.swing.JPanel jpConsultarSala;
    private javax.swing.JPanel jpResultadosdaBusca;
    private javax.swing.JTextField jtDadosdePesquisa;
    // End of variables declaration//GEN-END:variables
}
