/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Renato
 */
public class TelaConsultar extends javax.swing.JPanel {

    /**
     * Creates new form TelaReservas
     */
    public TelaConsultar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpConsultarSala = new javax.swing.JPanel();
        jtDadosdePesquisa = new javax.swing.JTextField();
        jlSubtituloData = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jTextArea1 = new javax.swing.JTextArea();
        jpResultadosdaBusca = new javax.swing.JPanel();
        txtConsultar = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistResultadosBusca = new javax.swing.JList<>();

        jpConsultarSala.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONSULTAR SALA", 2, 0, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jtDadosdePesquisa.setText("Informações da sala que você quer");
        jtDadosdePesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDadosdePesquisaActionPerformed(evt);
            }
        });

        jlSubtituloData.setText("Informe a data");

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Informe o código, o tipo ou uma palavra-chave para encontrar a sala que deseja consultar a disponibilidade.  ");
        jTextArea1.setWrapStyleWord(true);

        javax.swing.GroupLayout jpConsultarSalaLayout = new javax.swing.GroupLayout(jpConsultarSala);
        jpConsultarSala.setLayout(jpConsultarSalaLayout);
        jpConsultarSalaLayout.setHorizontalGroup(
            jpConsultarSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultarSalaLayout.createSequentialGroup()
                .addComponent(jlSubtituloData)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConsultarSalaLayout.createSequentialGroup()
                .addGroup(jpConsultarSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtDadosdePesquisa, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpConsultarSalaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextArea1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jpConsultarSalaLayout.setVerticalGroup(
            jpConsultarSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConsultarSalaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtDadosdePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlSubtituloData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpResultadosdaBusca.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESULTADOS DA BUSCA", 2, 0, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        txtConsultar.setLabel("Consultar");
        txtConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultarActionPerformed(evt);
            }
        });

        jlistResultadosBusca.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "A001   (3 horarios disponíveis)", "A002   (3 horarios disponíveis)", "A003   (3 horarios disponíveis)", "A004   (3 horarios disponíveis)", "A005   (3 horarios disponíveis)", "A006   (3 horarios disponíveis)", "A007   (3 horarios disponíveis)", "A008   (3 horarios disponíveis)", "A009   (3 horarios disponíveis)", "A010   (3 horarios disponíveis)", "A011   (3 horarios disponíveis)", "A001   (3 horarios disponíveis)", "A002   (3 horarios disponíveis)", "A003   (3 horarios disponíveis)", "A004   (3 horarios disponíveis)", "A005   (3 horarios disponíveis)", "A006   (3 horarios disponíveis)", "A007\t(3 horarios disponíveis)", "A008\t(3 horarios disponíveis)", "A009\t(3 horarios disponíveis)", "A010\t(3 horarios disponíveis)", "A011\t(3 horarios disponíveis)" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlistResultadosBusca.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlistResultadosBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlistResultadosBuscaMouseClicked(evt);
            }
        });
        jlistResultadosBusca.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlistResultadosBuscaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jlistResultadosBusca);

        javax.swing.GroupLayout jpResultadosdaBuscaLayout = new javax.swing.GroupLayout(jpResultadosdaBusca);
        jpResultadosdaBusca.setLayout(jpResultadosdaBuscaLayout);
        jpResultadosdaBuscaLayout.setHorizontalGroup(
            jpResultadosdaBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpResultadosdaBuscaLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(txtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
        );
        jpResultadosdaBuscaLayout.setVerticalGroup(
            jpResultadosdaBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpResultadosdaBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpConsultarSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpResultadosdaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpConsultarSala, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpResultadosdaBusca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtDadosdePesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDadosdePesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDadosdePesquisaActionPerformed

    private void txtConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultarActionPerformed

    private void jlistResultadosBuscaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlistResultadosBuscaValueChanged
    }//GEN-LAST:event_jlistResultadosBuscaValueChanged

    private void jlistResultadosBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlistResultadosBuscaMouseClicked
        if(evt.getClickCount()==2){
        System.out.println("teste "+ jlistResultadosBusca.getSelectedValue());
        DescricaoSala descricaosala = new DescricaoSala();
        descricaosala.setVisible(true);
        
        }
    }//GEN-LAST:event_jlistResultadosBuscaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jlSubtituloData;
    private javax.swing.JList<String> jlistResultadosBusca;
    private javax.swing.JPanel jpConsultarSala;
    private javax.swing.JPanel jpResultadosdaBusca;
    private javax.swing.JTextField jtDadosdePesquisa;
    private java.awt.Button txtConsultar;
    // End of variables declaration//GEN-END:variables
}
